### PR TITLE
fix arrow functions

### PR DESCRIPTION
**Pull request by geovanerocha**

### CODE REVIEW

**Comment by zenorocha** [comment]
@abiduzz420 can you review and make sure everything is working?

**Comment by zenorocha** [comment]
Thanks a lot @geovanerocha ;)

**Comment by abiduzz420** [comment]
Heyy @geovanerocha Thanks for submitting a PR! The code changes seem pretty good, will get it merged within few hours. Could you @geovanerocha please check out the `columns.js` file. I find red marks in the file.
I also see red marks in `src/scripts/home.js` file, probably some issue with code formatting.

**Comment by geovanerocha** [comment]
Nevermind guys, I'll work tonight and I fix the code of home.js :)

**Comment by geovanerocha** [comment]
[@abiduzz420 @zenorocha]  I saw on branch master that this issue was old, so can I standardize the code identation on JS files? or maybe it's a github code highlight bug, because I see on my branch and it seems ok, see this stackoverflow thread: https://stackoverflow.com/questions/30667675/what-does-a-red-text-background-mean-in-github-comparison-view

**Comment by geovanerocha** [comment]
@abiduzz420 I've made some tests and the single quote was making the code highlight weird, so I change to HTML entity` &apos;` in home.js and columns.js =)

**Comment by abiduzz420** [comment]
@geovanerocha I am in the process of update many packages, since a lot of them are deprecated. I shall merge your PR soon :)

**Review by abiduzz420 — APPROVED** [review]
Thanks @geovanerocha

**Pull request merged**
